/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Airline_Reservation_System;
import java.util.ArrayList;
import java.sql.*;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
/**
 *
 * @author deepu
 */
public class Domestic_Flights extends javax.swing.JFrame {

    /**
     * Creates new form Domestic_Flights
     */
    public Domestic_Flights() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        l7 = new javax.swing.JLabel();
        c7 = new javax.swing.JComboBox();
        c6 = new javax.swing.JComboBox();
        l6 = new javax.swing.JLabel();
        btn1 = new javax.swing.JButton();
        c5 = new javax.swing.JComboBox();
        c4 = new javax.swing.JComboBox();
        c3 = new javax.swing.JComboBox();
        c2 = new javax.swing.JComboBox();
        c1 = new javax.swing.JComboBox();
        l5 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        l7.setText("Class");
        jPanel1.add(l7);
        l7.setBounds(310, 184, 60, 30);

        c7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ECONOMY", "PREMIUM ECONOMY", "BUSINESS" }));
        jPanel1.add(c7);
        c7.setBounds(380, 190, 180, 30);

        c6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kingfisher", "Jet Airways", "SpiceJet", "Air India", "IndiGo" }));
        jPanel1.add(c6);
        c6.setBounds(170, 190, 100, 30);

        l6.setText("Flight name");
        jPanel1.add(l6);
        l6.setBounds(50, 190, 70, 30);

        btn1.setText("Continue");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn1);
        btn1.setBounds(250, 263, 140, 30);

        c5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Chennai", "Bangalore", "Thirupathi", " " }));
        jPanel1.add(c5);
        c5.setBounds(410, 60, 130, 30);

        c4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hyderabad", "Mumbai", "Kolkata", " " }));
        jPanel1.add(c4);
        c4.setBounds(130, 60, 130, 30);

        c3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2015", "2016", "2017" }));
        jPanel1.add(c3);
        c3.setBounds(430, 120, 90, 30);

        c2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC" }));
        jPanel1.add(c2);
        c2.setBounds(270, 120, 110, 30);

        c1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", " " }));
        jPanel1.add(c1);
        c1.setBounds(160, 120, 60, 30);

        l5.setText("Date of journey");
        jPanel1.add(l5);
        l5.setBounds(50, 120, 110, 30);

        l4.setText("To");
        jPanel1.add(l4);
        l4.setBounds(350, 60, 30, 30);

        l3.setText("From");
        jPanel1.add(l3);
        l3.setBounds(50, 70, 50, 20);

        l2.setText("DOMESTIC FLIGHTS");
        jPanel1.add(l2);
        l2.setBounds(230, 10, 150, 30);

        l1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Airline_Reservation_System/background_loginpage.jpg"))); // NOI18N
        jPanel1.add(l1);
        l1.setBounds(0, 0, 600, 380);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        
        Payment p = new Payment();
        p.setVisible(true);
    }//GEN-LAST:event_btn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Domestic_Flights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Domestic_Flights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Domestic_Flights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Domestic_Flights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Domestic_Flights().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JComboBox c1;
    private javax.swing.JComboBox c2;
    private javax.swing.JComboBox c3;
    private javax.swing.JComboBox c4;
    private javax.swing.JComboBox c5;
    private javax.swing.JComboBox c6;
    private javax.swing.JComboBox c7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l7;
    // End of variables declaration//GEN-END:variables
}
