/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Airline_Reservation_System;
import java.sql.*;
import javax.swing.*;
import java.awt.*;
/**
 *
 * @author deepu
 */
public class New_User extends javax.swing.JFrame {
Connection con=null;
    PreparedStatement pst=null;
    /**
     * Creates new form New_User
     */
    public New_User() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        c1 = new javax.swing.JComboBox();
        btn1 = new javax.swing.JButton();
        p2 = new javax.swing.JPasswordField();
        p1 = new javax.swing.JPasswordField();
        t2 = new javax.swing.JTextField();
        t1 = new javax.swing.JTextField();
        l9 = new javax.swing.JLabel();
        l8 = new javax.swing.JLabel();
        l7 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        c1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "India" }));
        jPanel1.add(c1);
        c1.setBounds(160, 270, 70, 20);

        btn1.setText("Create Account & Continue");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn1);
        btn1.setBounds(170, 480, 190, 50);
        jPanel1.add(p2);
        p2.setBounds(160, 420, 120, 20);

        p1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1ActionPerformed(evt);
            }
        });
        jPanel1.add(p1);
        p1.setBounds(160, 370, 120, 20);
        jPanel1.add(t2);
        t2.setBounds(160, 210, 190, 20);
        jPanel1.add(t1);
        t1.setBounds(160, 150, 90, 20);

        l9.setText("Confirm Password");
        jPanel1.add(l9);
        l9.setBounds(20, 420, 120, 14);

        l8.setText(" Password");
        jPanel1.add(l8);
        l8.setBounds(20, 370, 90, 14);

        l7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l7.setText("Password Information:");
        jPanel1.add(l7);
        l7.setBounds(20, 320, 190, 22);

        l6.setText("Citizen of");
        jPanel1.add(l6);
        l6.setBounds(20, 270, 70, 14);

        l5.setText("Email Address");
        jPanel1.add(l5);
        l5.setBounds(10, 210, 90, 14);

        l3.setText("Name");
        jPanel1.add(l3);
        l3.setBounds(20, 150, 50, 14);

        l2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l2.setText("Personal Information:");
        jPanel1.add(l2);
        l2.setBounds(20, 80, 200, 40);

        l1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Airline_Reservation_System/login-page.jpg"))); // NOI18N
        jPanel1.add(l1);
        l1.setBounds(0, 0, 500, 580);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void p1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p1ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        if(p1.getText().equals(p2.getText())){
        try{
           
			Class.forName("com.mysql.jdbc.Driver");
		con = DriverManager.getConnection("jdbc:mysql://localhost:3306/deepika","root","password");
           String sql = "insert into LOGIN(UserName,Password) value(?,?)";
           pst=con.prepareStatement(sql);
           pst.setString(1,t1.getText());
           pst.setString(2,p1.getText());
           
           
           pst.execute();
           
           Main_Page m=new Main_Page();
           m.setVisible(true);
           m.getContentPane();
           
        }
        catch(Exception e){
             JOptionPane.showMessageDialog(null,e);
         
        }}
        else{
       JOptionPane.showMessageDialog(this,"Passwords did not match please try again","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        
              
    }//GEN-LAST:event_btn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(New_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(New_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(New_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(New_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new New_User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JComboBox c1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l8;
    private javax.swing.JLabel l9;
    private javax.swing.JPasswordField p1;
    private javax.swing.JPasswordField p2;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    // End of variables declaration//GEN-END:variables
}
